name: Build and Deploy Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Buildah
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ secrets.DOCKER_IMAGE }}
          tags: ${{ secrets.DOCKER_TAG }}
          containerfiles: apps/server/Containerfile
          context: apps/server
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Push image to Docker Hub
        run: |
          buildah login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} docker.io &&
          buildah push ${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_TAG }} docker://${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_TAG }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client and sshpass
        run: sudo apt-get update && sudo apt-get install -y openssh-client sshpass

      - name: Deploy on remote server using password
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            docker pull ${{ secrets.DOCKER_IMAGE }} && \
            cd ${{ secrets.DOCKER_COMPOSE_PATH }} && \
            docker compose down && \
            docker compose up -d
          '
